# Generated by Django 5.2.1 on 2025-05-10 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=16, verbose_name='Created by')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('modified_by', models.CharField(blank=True, max_length=16, verbose_name='Last modified by')),
                ('note', models.TextField(null=True, verbose_name='Note')),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Currency Code')),
                ('name', models.CharField(max_length=30, verbose_name='Short Description')),
                ('iso_code', models.CharField(max_length=3, unique=True, verbose_name='ISO')),
                ('numeric_code', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('telegram_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'telegram user',
                'verbose_name_plural': 'Telegram Users',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=16, verbose_name='Created by')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('modified_by', models.CharField(blank=True, max_length=16, verbose_name='Last modified by')),
                ('rate_date', models.DateField()),
                ('nominal', models.PositiveSmallIntegerField(default=1)),
                ('rate', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='common.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
                'ordering': ['-rate_date', 'currency'],
                'unique_together': {('currency', 'rate_date')},
            },
        ),
    ]
