# Generated by Django 5.2.1 on 2025-05-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=16, verbose_name='Created by')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('modified_by', models.CharField(blank=True, max_length=16, verbose_name='Last modified by')),
                ('note', models.TextField(null=True, verbose_name='Note')),
                ('item_id', models.CharField(max_length=50, unique=True, verbose_name='Item ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.CharField(choices=[('Produced', 'Produced'), ('Purchased', 'Purchased'), ('Services', 'Services')], default='Purchased', max_length=20, verbose_name='Item Type')),
                ('unit_of_measure', models.CharField(choices=[('klg.', 'Kilograms'), ('ltr.', 'Liters'), ('mtr.', 'Meters'), ('min.', 'Minutes'), ('pcs.', 'Pieces')], default='pcs.', max_length=4, verbose_name='Unit of Measure')),
                ('cost_price', models.FloatField(default=0, verbose_name='Cost Price')),
                ('weight', models.FloatField(default=0, verbose_name='Weight')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'Items',
                'ordering': ['item_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['user__username', 'telegram_id'], 'verbose_name': 'telegram user', 'verbose_name_plural': 'Telegram Users'},
        ),
    ]
