# Generated by Django 5.2.1 on 2025-05-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_item_alter_telegramuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Description'),
        ),
    ]
