# Generated by Django 5.2.1 on 2025-05-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='item_images', verbose_name='Item image'),
        ),
    ]
