# Generated by Django 5.2.1 on 2025-05-17 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.CharField(max_length=16, verbose_name='Created by')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('modified_by', models.CharField(blank=True, max_length=16, verbose_name='Last modified by')),
                ('bom_quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Bom Quantity')),
                ('main_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_items', to='common.item', verbose_name='Main Item')),
                ('sub_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='common.item', verbose_name='Sub Item')),
            ],
            options={
                'verbose_name': 'BOM Item',
                'verbose_name_plural': 'BOM Items',
                'ordering': ['main_item', 'sub_item'],
            },
        ),
    ]
