# Generated by Django 5.2.1 on 2025-05-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_itembom_unique_main_sub_items_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itembom',
            name='prevent_self_follow',
        ),
        migrations.AddConstraint(
            model_name='itembom',
            constraint=models.CheckConstraint(condition=models.Q(('main_item', models.F('sub_item')), _negated=True), name='prevent_self_item'),
        ),
    ]
